name: Github Actions Demo
run-name: ABC
permissions:
  pull-requests: write
on:
  push:
    branches:
      - main

env:
  TF_VERSION: "1.15"

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      WITAMY: witanko powitanko
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332
      - uses: docker/metadata-action@v6.2.0
        id: meta
        with:
          images: bajlando
          tags: |
            type=sha,prefix=,format=short
        env:
          DOCKER_METADATA_PR_HEAD_SHA: true

      - run: echo ${{ steps.meta.outputs.tags }}

