name: Github Actions Demo
run-name: ABC
permissions:
  pull-requests: write
on:
  push:
    branches:
      - main

env:
  TF_VERSION: "1.15"

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      WITAMY: witanko powitanko
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332
      - name: Show checked out commit
        run: |
          echo "GITHUB_SHA: $GITHUB_SHA"
          echo "GITHUB_REF: $GITHUB_REF"
          echo "GITHUB_EVENT_NAME: $GITHUB_EVENT_NAME"
          echo "HEAD: $(git rev-parse HEAD)"
          echo "HEAD commit:"
          git show -s --format='%H %P %s' HEAD

