name: Github Actions Demo
run-name: ABC
permissions:
  pull-requests: write
on:
  push:
    branches:
      - main

env:
  TF_VERSION: "1.15"

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      WITAMY: witanko powitanko
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332
      - run: echo "BUILD"

  testing:
    runs-on: ubuntu-last
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332
      - run: echo "TESTING"


  plan:
    environment: staging
    runs-on: ubuntu-last
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332
      - run: echo "PLANNING"

  apply:
    environment: staging
    runs-on: ubuntu-last
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332
      - run: echo "PLANNING"
